# Generated by Django 3.1.7 on 2021-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('address', models.TextField(max_length=400)),
                ('city', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Allahbad', 'Allahbad'), ('Chennai', 'Chennai'), ('Agra', 'Agra'), ('Rameshwaram', 'Rameshwaram'), ('Hyderabad', 'Hyderabad'), ('Goa', 'Goa')], max_length=30)),
                ('date', models.DateField()),
                ('travellers', models.PositiveIntegerField()),
                ('flight_class', models.CharField(max_length=20)),
                ('budget', models.FloatField()),
                ('id_proof', models.ImageField(upload_to='')),
                ('additional', models.CharField(max_length=20)),
                ('student', models.BooleanField()),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
