# Generated by Django 3.1.7 on 2021-04-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional',
            field=models.CharField(choices=[('F', 'Food'), ('N', 'Non-Stop'), ('R', 'Refundable')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Allahbad', 'Allahbad'), ('Chennai', 'Chennai'), ('Agra', 'Agra'), ('Rameshwaram', 'Rameshwaram'), ('Hyderabad', 'Hyderabad'), ('Goa', 'Goa')], default='Delhi', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_class',
            field=models.CharField(choices=[('E', 'Economy'), ('P', 'Premium Economy'), ('B', 'Business')], default='E', max_length=20),
        ),
    ]
