# Generated by Django 3.1.7 on 2021-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210501_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional',
            field=models.CharField(max_length=20),
        ),
    ]
