# Generated by Django 3.1.7 on 2021-05-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210501_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
